### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by excalamus** [EPLHREU/emily-symbols#4]
Am I free to modify and publish the code/resources of emily-symbols?

I've been (slowly) creating [a dictionary for use with Emacs](https://github.com/excalamus/plover-emacs) which extensively provides definitions for modified keys.  Having done this for the alphabet, my next hurdle was to address symbols.  That's now been solved by you.  I cannot thank you enough!  I would like to know if I can incorporate your ideas and code into my own dictionary. 

PS: How did you generate the layout diagrams?

Best wishes,
Matt

**Comment by EPLHREU** [comment]
Yes, of course you are able to publish and make your own version of this, I created and presented it mainly as an idea, which I have just made a default setup for. 
It would be nice to reference it back here in case people come across your work and wonder how it could be used outside of emacs specifically, or if it might have been updated since.

I actually came across your repository the other day following some discussion of emacs + plover in the plover discord server.
It's some great working you're doing and I've actually been coming up with my own idea for a dictionary that uses keyboard shortcuts all in one stroke, in a similar vein to what you have started :)
It may or may not be helpful to write up your dictionary in a python-dictionary format for use with plover, that way you can programatically make changes to it, much like this dictionary is.

I used http://www.keyboard-layout-editor.com to make all the diagrams.
Added legends, coloured the keys then exported the layout as a png directly.
Once on that website, if you go to the "Raw data" tab under the keyboard layout, and click on "Upload JSON"; selecting stuff/layout.json in this repository will load up the main layout diagram I created all the diagrams from with colours and all!

**Comment by excalamus** [comment]
Great!  I didn't want to assume and felt it was an opportunity to say thanks.  I will happily provide a reference.

I [tried to automate the dictionary creation](https://github.com/excalamus/plover-emacs/commit/6bc6a456506c69e5eeb54dba237355bcc7ea4dae#diff-836ed9adc01232042a4a138877199aa07ee3bcfb0b9e8cab0c5c5f161a1c4f66L443) but found it was distracting me from my primary goal (actually creating the dictionary).  One of the appeals of your repo is that I may be able to modify your Python code for myself.  Or, are you talking about a Plover dictionary format that's non-json and is instead a Python dict?

I'm glad to hear people are discussing the use of Plover with Emacs.  Unfortunately, I've been staying away from Discord in the name of free software (really, I don't want to remember *another* password).  Maybe some day Plover will have free community gathering places (not Google Groups, Discord, Reddit, GitHub, etc.)...

**Comment by EPLHREU** [comment]
your thanks is very much appreciated, i'm just glad i'm able to help people out with something.

ooh, that generation looks interesting. Might have to have a go a putting it in lisp in the future :p 
Yeah, I was referring to a python dictionary for plover, as in your repo you just seem to have a json file with all the entries you need. From making these dictionaries i found it much nicer to do it all programatically, as i can make a simple change and it will updated to all potential chords, rather than updating a list of hundreds of chords manually. But if you're not using the json with use with plover then that makes sense.

Yeah, it's really cool to see - there's actually been a few new users looking specifically plover+emacs which is really cool to see. 
That decision makes sense, here's hoping the plover and steno community expands out to more free platforms - that'd be nice. :)

**Comment by excalamus** [comment]
Absolutely, you're welcome.  

I'm going to close this as, someone once said, "issues are not for extended discussion."  If you'd like to continue talking shop, feel free to drop me an email (excalamus@tutanota.com).  Thanks again and hopefully I can get time soon do develop the Plover-Emacs dictionary a little more.
